services:
  # merchant-api:
  #   build:
  #     context: ./docker
  #     dockerfile: Dockerfile.dev
  #   container_name: merchant-api
  #   restart: always
  #   env_file:
  #     - .env
  #   ports:
  #     - '${APP_PORT}:${APP_PORT}'
  #   depends_on:
  #     - merchant-db-api
  #   networks:
  #     - net_merchant_api
  #   volumes:
  #     - .:/usr/src/app
  #     - /app/node_modules
  #   logging:
  #     driver: 'json-file'
  #     options:
  #       max-size: '100m'
  #       max-file: '5'

  merchant-db-api:
    image: mysql:latest
    container_name: merchant-db-api
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=merchant_db
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    networks:
      - net_merchant_api
    ports:
      - '3306:3306'
    volumes:
      - merchant_db_mysql:/var/lib/mysql

  merchant-adminer:
    image: adminer
    container_name: merchant-adminer
    restart: always
    ports:
      - '8080:8080'
    networks:
      - net_merchant_api

networks:
  net_merchant_api:
    driver: bridge

volumes:
  merchant_db_mysql:
    driver: local
