FROM node:22.8.0-alpine3.20

RUN apk add --no-cache alpine-conf && \
    setup-timezone -z Asia/Jakarta && \
    rm -rf /var/cache/apk/*

LABEL maintainer="Ruben Alpredo Tampubolon"

WORKDIR /app

ENV NODE_ENV development

ENV TZ Asia/Jakarta

COPY package.json ./

COPY . .

RUN cp .env.example .env

# Install dependencies
RUN npm install && npm cache clean --force

# Expose the port defined in the .env file
# Using the environment variable syntax to read the PORT from the .env file
ARG APP_PORT
EXPOSE $APP_PORT

# Start the application
CMD ["npm", "run", "dev"]